In [17]:
import numpy as np
Arr = np.array(( 2, 2));
print("the empty array 2X2 is : " , Arr)


one_arr = np.ones((4 , 2));
print("the 4X2 array with ones are: ");
print(one_arr)

Arr_full = np.full((3,9),199);
print("the 3x9 array of value 199 is");
print(Arr_full);

Arr_given = ([[2,8],[7,9]]);
zero_array = np.zeros_like(Arr_given)
print(zero_array)

Arr_GIVEN = ([[2,3], [53,2],[32,42]]);
one_arr = np.ones_like(Arr_GIVEN);
print("ones array are");
print(one_arr)


new_list=[1,3,5,5,7,8,9,0];
arrConvert = np.array(new_list);
print("the converted list into array is: ", arrConvert)



the empty array 2X2 is :  [2 2]
the 4X2 array with ones are: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
the 3x9 array of value 199 is
[[199 199 199 199 199 199 199 199 199]
 [199 199 199 199 199 199 199 199 199]
 [199 199 199 199 199 199 199 199 199]]
[[0 0]
 [0 0]]
ones array are
[[1 1]
 [1 1]
 [1 1]]
the converted list into array is:  [1 3 5 5 7 8 9 0]


In [47]:
#problem 2
import numpy as np
arrangedArr= np.arange(10,50);
print("the arranged array are: " , arrangedArr);


Matric = np.arange(0,9);
arr_m = Matric.reshape(3,3);
print("the matric from 0 to 9 in 3x3 is ", arr_m)

IdentityMatrix = np.eye(3);
print("the identity matrix is \n\n" , IdentityMatrix)


ran_arr = np.random.random(30);
mean_ran = ran_arr.mean()
print("the random array of 30 size and mean is ", ran_arr, mean_ran);



ran_ten = np.random.random((10,10));
min_val = ran_ten.min();
max_val = ran_ten.max();

print("the min value is :" , min_val, "max value is : ", max_val, "of", ran_ten)



zero_arr = np.zeros(10);
zero_arr[4] = 1
print("5th replaced by 1 element is");
print(zero_arr);



arr = np.array([1,2,0,0,4,0])
rev_arr = arr[::-1]

print("reversed array is \n", rev_arr)




arr= np.ones((5,5));
arr[1:-1,1:-1]=0
print("the array of 1 border is ")
print(arr);

checkerboard = np.zeros((8,8));
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print("the checker baord is : " , checkerboard);




the arranged array are:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
the matric from 0 to 9 in 3x3 is  [[0 1 2]
 [3 4 5]
 [6 7 8]]
the identity matrix is 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
the random array of 30 size and mean is  [0.64973359 0.68833894 0.18251434 0.30249469 0.83266963 0.28501211
 0.99663955 0.29876804 0.8836366  0.23915816 0.41616386 0.74882157
 0.91870316 0.75067902 0.71603106 0.03754278 0.57508761 0.56884679
 0.25381762 0.69009487 0.78734692 0.45728932 0.2807324  0.19887369
 0.70441442 0.90276082 0.76086547 0.43913145 0.53679427 0.67191924] 0.5591627323222526
the min value is : 0.023204244703198706 max value is :  0.9894476871584769 of [[0.46333422 0.29843925 0.27216511 0.58856457 0.18427568 0.2190107
  0.69385269 0.80771368 0.71673699 0.9757124 ]
 [0.58022707 0.38605799 0.98561815 0.40266027 0.24669308 0.84850071
  0.302374   0.14890065 0.08419571 0.08698178]
 [0.38624349 0.75375258 

In [50]:
#PROBLEM 3
x = np.array([[1,2],[3,5]])
y= np.array([[5,6],[7,8]]);
v = np.array([9, 10])
w = np.array([11, 12])

add = x + y;
#sum
print("sum" , add);

#subtract
sub = x-y;
print("sub",sub);

#multiply
multiply = x*55;
print("the multiplication is " , multiply);

square = np.square(x);
print("the sqaure is", square);


#dotproduct
dot_pro= np.dot(v,w);
print("the dot product betn 2 numbers are : " , dot_pro)



dot_pro= np.dot(x,v);
print("the dot product betn 2 numbers are : " , dot_pro)


dot_pro= np.dot(x,y);
print("the dot product betn 2 numbers are : " , dot_pro)



#concatenate
mat   = np.concatenate((x,y ), axis = 0);
print(mat);
mat   = np.concatenate((v.reshape(-1,1) ), axis = 1);
print(mat);







sum [[ 6  8]
 [10 13]]
sub [[-4 -4]
 [-4 -3]]
the multiplication is  [[ 55 110]
 [165 275]]
the sqaure is [[ 1  4]
 [ 9 25]]
the dot product betn 2 numbers are :  219
the dot product betn 2 numbers are :  [29 77]
the dot product betn 2 numbers are :  [[19 22]
 [50 58]]


In [64]:
#PROBLEM 4

import numpy as np

A = np.array([[3,4],[7,4]])
B= np.array([[5,3],[2,1]])

#A>A^-1 = I
InverseA = np.linalg.inv(A);
#prove a*a-1 = I
I=np.dot(A, InverseA)
print(I)


#AB cross muitply 

AB = np.dot(A, B);
BA = np.dot(B,A);

#AB = BA?
equal = np.array_equal(AB,BA);
print(equal)


TransAB = np.transpose(AB);
BT = np.transpose(B);
AT = np.transpose(A);

BTAT = np.dot(BT, AT);

#ABt = BTAT
print(TransAB)
print(BTAT)


A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])

B= np.array([-1,-3,9])


# X = A-1*B
InverseA = np.linalg.inv(A);

X = np.dot(InverseA,B);

#using inverse method
print(X[0])
print(X[1])
print(X[2])




[[1. 0.]
 [0. 1.]]
False
[[23 43]
 [13 25]]
[[23 43]
 [13 25]]
1.9999999999999998
1.0000000000000004
-1.9999999999999996


In [11]:
#comparee
import time

import numpy as np
size=1000000

list1 = [i for i in range(size)]
list2 = [i *2 for i in range(size)]

start = time.time()
sum = [list1[i]+ list2[i] for i in range(size)];
end= time.time()

print(f"the addition of elements took: {end - start:.8f} seconds")


arr1 = np.arange(size)
arr2= np.arange(size)*2
start = time.time()
sum = arr1 + arr2
end = time.time()
print(f"the addition of elements took: {end - start:.8f} seconds")



start = time.time()

list_pro = [list1[i] * list2[i] for i in range(size)]
end = time.time()

print(f"the multiplication of elements took: {end - start:.8f} seconds")


start = time.time()
arr_pro = arr1 + arr2
end = time.time()

print(f"the multiplication of elements took: {end - start:.8f} seconds")

#dot product
start = time.time()
dot_pro = np.dot(list1, list2)
end = time.time()
print(f"the product of elements took: {end - start:.8f} seconds")



start = time.time()
dot_pro = [[sum(list1[i] * list2[i] for i in range(size))]]
end = time.time()
end = time.time()
print(f"the product of elements took: {end - start:.8f} seconds")


# start = time.time()
# dot_pro = np.dot(list1, list2)
# end = time.time()
# print(f"the product of elements took: {end - start:.8f} seconds")



#matrix multiplication
#numpy
size = 1000
A = np.random.randint(1,10,(size, size))
B= np.random.randint(1,10,(size, size))

start = time.time()
np.dot(A,B)
end = time.time()

print(f"The matrix mulitplicaiton took {end - start:.8f} seconds")


#matrix multiplication
#normal


mat_a = [[i for i in range(size)] for j in range(size)]
mat_b = [[i + 1 for i in range(size)] for j in range(size)]

start_time = time.time()
product_matrix = [[sum(mat_a[i][k] * mat_b[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
list_multiplication_time = end_time - start_time
print(f"Time taken for matrix multiplication using lists: {list_multiplication_time:.5f} seconds")

rand_mat1 = np.random.rand(size, size)
rand_mat2 = np.random.rand(size, size)

start_time2 = time.time()
product_numpy = np.dot(rand_mat1, rand_mat2)
end_time2 = time.time()
numpy_multiplication_time = end_time2 - start_time2
print(f"Time taken for matrix multiplication using NumPy: {numpy_multiplication_time:.5f} seconds")





the addition of elements took: 0.11000013 seconds
the addition of elements took: 0.03100014 seconds
the multiplication of elements took: 0.14700007 seconds
the multiplication of elements took: 0.00199986 seconds
the product of elements took: 0.17100000 seconds


<class 'TypeError'>: 'numpy.ndarray' object is not callable

<class 'TypeError'>: 'numpy.ndarray' object is not callable

<class 'TypeError'>: 'numpy.ndarray' object is not callable